export const MOCK_APPLICATIONS_LIST = [
  {
    name: 'Tanya Treutel',
    university: 'Loughborough University',
    country: 'Armenia',
    duration: '1 year',
    cost: 158885,
    applicationDeadlineDate: new Date('2029-09-03T03:49:22.161Z'),
    language: 'English',
  },
  {
    name: 'Dewey Feest',
    university: 'Loughborough University',
    country: 'Saint Martin',
    duration: '5 years',
    cost: 54112,
    applicationDeadlineDate: new Date('2026-06-28T00:48:28.166Z'),
    language: 'French',
  },
  {
    name: 'Kelli Wisozk',
    university: 'Loughborough University',
    country: 'Chile',
    duration: '8 years',
    cost: 256553,
    applicationDeadlineDate: new Date('2029-02-07T14:39:45.777Z'),
    language: 'English',
  },
  {
    name: 'Mr. Wendell Schuppe Sr.',
    university: 'University of Oxford',
    country: 'Sint Maarten',
    duration: '5 years',
    cost: 23916,
    applicationDeadlineDate: new Date('2024-03-06T07:47:31.456Z'),
    language: 'Turkish',
  },
  {
    name: 'Ellis Adams',
    university: 'London School of Economics',
    country: 'Guyana',
    duration: '4 years',
    cost: 274320,
    applicationDeadlineDate: new Date('2028-05-07T18:04:28.441Z'),
    language: 'Turkish',
  },
];
